CREATE SCHEMA IF NOT EXISTS produto_db;
CREATE SCHEMA IF NOT EXISTS carrinho_db;
CREATE SCHEMA IF NOT EXISTS pedido_db;
CREATE SCHEMA IF NOT EXISTS estoque_db;
CREATE SCHEMA IF NOT EXISTS pagamento_db;
CREATE SCHEMA IF NOT EXISTS notificacao_db;
